@export
Program = body:Block;

Block = {statements:Statement};

Statement = @:PrintStatement | @:EndStatement | @:Assignment;

# Expression
Expression = ( term:VariableName | term: NumberLiteral );


# ASSIGNMENT
Assignment = variable:VariableName "=" ( value:NumberLiteral | value:StringLiteral );

# PRINT
PrintStatement = KWPrint ( list:Expression | list:StringLiteral );

# END
EndStatement  = KWEnd;

# KEYWORDS
KWPrint = 'PRINT';
KWEnd = 'END';

# Variable
@string
VariableName = ( >ALPHA | "_" | "`" ) { >ALPHA | >DIGIT | "_" | "%" | "$" };

# LITERALS
NumberSign = '+' | '-';
NumberLiteral = value:FloatLiteral | value:IntegerLiteral;

@string
IntegerLiteral = [NumberSign] {'0'..'9'}+;

@string
FloatLiteral = [NumberSign] { >DIGIT }+ "." { >DIGIT} [ 'E' { >DIGIT }+ ];

@no_skip_ws
StringLiteral = '"' body:StringBody '"';

@string
StringBody = {!'"' char};


# Basics
ALPHA = 'a'..'z' | 'A'..'Z';
DIGIT = '0'..'9';